//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyanu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atiklar
    {
        public int AtikId { get; set; }
        public Nullable<int> UrunId { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
