//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyanu
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolumZimmet
    {
        public int BolumZimmetId { get; set; }
        public int BolumId { get; set; }
        public int UrunId { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
