//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyanu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Atiklars = new HashSet<Atiklar>();
            this.BolumZimmets = new HashSet<BolumZimmet>();
            this.KisiZimmets = new HashSet<KisiZimmet>();
        }
    
        public int UrunId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> TedarikciId { get; set; }
        public string UrunaAdi { get; set; }
        public decimal UrunBirimFiyati { get; set; }
        public Nullable<System.DateTime> SatinAlinmaTarihi { get; set; }
        public int Stok { get; set; }
        public bool StokDurum { get; set; }
        public Nullable<int> BolumID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atiklar> Atiklars { get; set; }
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolumZimmet> BolumZimmets { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiZimmet> KisiZimmets { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
